#ifndef MT_PRIM_LIMITS_H
#define MT_PRIM_LIMITS_H

#include <float.h>
#include <stdint.h>
#include <limits.h>

#define M_CHAR_WIDTH CHAR_BIT

// Char:

#define M_CHAR_MIN  CHAR_MIN
#define M_CHAR_MAX  CHAR_MAX
#define M_UCHAR_MAX UCHAR_MAX
#define M_SCHAR_MIN SCHAR_MIN
#define M_SCHAR_MAX SCHAR_MAX

// Int:

#define M_SINT_MIN   SHRT_MIN
#define M_SINT_MAX   SHRT_MAX
#define M_USINT_MAX  USHRT_MAX
#define M_INT_MIN    INT_MIN
#define M_INT_MAX    INT_MAX
#define M_UINT_MAX   UINT_MAX
#define M_LINT_MIN   LONG_MIN
#define M_LINT_MAX   LONG_MAX
#define M_ULINT_MAX  ULONG_MAX
#define M_LLINT_MIN  LLONG_MIN
#define M_LLINT_MAX  LLONG_MAX
#define M_ULLINT_MAX ULLONG_MAX

// Float:

#define M_FLOAT_RADIX FLT_RADIX

#define M_FLOAT_DECIMAL_DIG   FLT_DECIMAL_DIG
#define M_DOUBLE_DECIMAL_DIG  DBL_DECIAML_DIG
#define M_LDOUBLE_DECIMAL_DIG LDBL_DECIMAL_DIG

#define M_FLOAT_DIG   FLT_DIG
#define M_DOUBLE_DIG  DBL_DIG
#define M_LDOUBLE_DIG LDBL_DIG

#define M_FLOAT_MANT_DIG   FLT_MANT_DIG
#define M_DOUBLE_MANT_DIG  DBL_MANT_DIG
#define M_LDOUBLE_MANT_DIG LDBL_MANT_DIG

#define M_FLOAT_MIN_EXP      FLT_MIN_EXP
#define M_FLOAT_MIN_10_EXP   FLT_MIN_10_EXP
#define M_FLOAT_MAX_EXP      FLT_MAX_EXP
#define M_FLOAT_MAX_10_EXP   FLT_MAX_10_EXP
#define M_DOUBLE_MIN_EXP     DBL_MIN_EXP
#define M_DOUBLE_MIN_10_EXP  DBL_MIN_10_EXP
#define M_DOUBLE_MAX_EXP     DBL_MAX_EXP
#define M_DOUBLE_MAX_10_EXP  DBL_MAX_10_EXP
#define M_LDOUBLE_MIN_EXP    LDBL_MIN_EXP
#define M_LDOUBLE_MIN_10_EXP LDBL_MIN_10_EXP
#define M_LDOUBLE_MAX_EXP    LDBL_MAX_EXP
#define M_LDOUBLE_MAX_10_EXP LDBL_MAX_10_EXP

#define M_FLOAT_MIN        FLT_MIN
#define M_FLOAT_TRUE_MIN   FLT_TRUE_MIN
#define M_FLOAT_MAX        FLT_MAX
#define M_DOUBLE_MIN       DBL_MIN
#define M_DOUBLE_TRUE_MIN  DBL_TRUE_MIN
#define M_DOUBLE_MAX       DBL_MAX
#define M_LDOUBLE_MIN      LDBL_MIN
#define M_LDOUBLE_TRUE_MIN LDBL_TRUE_MIN
#define M_LDOUBLE_MAX      LDBL_MAX

#define M_FLOAT_EPSILON   FLT_EPSILON
#define M_DOUBLE_EPSILON  DBL_EPSILON
#define M_LDOUBLE_EPSILON LDBL_EPSILON

#define M_FLOAT_ROUNDS      FLT_ROUNDS
#define M_FLOAT_EVAL_METHOD FLT_EVAL_METHOD

#define M_FLOAT_HAS_SUBNORM   FLT_HAS_SUBNORM
#define M_DOUBLE_HAS_SUBNORM  DBL_HAS_SUBNORM
#define M_LDOUBLE_HAS_SUBNORM LDBL_HAS_SUBNORM

// Fixed:

#define M_INT8_MIN   INT8_MIN
#define M_INT8_MAX   INT8_MAX
#define M_UINT8_MAX  UINT8_MAX
#define M_INT16_MIN  INT16_MIN
#define M_INT16_MAX  INT16_MAX
#define M_UINT16_MAX UINT16_MAX
#define M_INT32_MIN  INT32_MIN
#define M_INT32_MAX  INT32_MAX
#define M_UINT32_MAX UINT32_MAX
#define M_INT64_MIN  INT64_MIN
#define M_INT64_MAX  INT64_MAX
#define M_UINT64_MAX UINT64_MAX

// Fast:

#define M_FAST8_MIN   INT_FAST8_MIN
#define M_FAST8_MAX   INT_FAST8_MAX
#define M_UFAST8_MAX  UINT_FAST8_MAX
#define M_FAST16_MIN  INT_FAST16_MIN
#define M_FAST16_MAX  INT_FAST16_MAX
#define M_UFAST16_MAX UINT_FAST16_MAX
#define M_FAST32_MIN  INT_FAST32_MIN
#define M_FAST32_MAX  INT_FAST32_MAX
#define M_UFAST32_MAX UINT_FAST32_MAX
#define M_FAST64_MIN  INT_FAST64_MIN
#define M_FAST64_MAX  INT_FAST64_MAX
#define M_UFAST64_MAX UINT_FAST64_MAX

// Least:

#define M_LEAST8_MIN   INT_LEAST8_MIN
#define M_LEAST8_MAX   INT_LEAST8_MAX
#define M_ULEAST8_MAX  UINT_LEAST8_MAX
#define M_LEAST16_MIN  INT_LEAST16_MIN
#define M_LEAST16_MAX  INT_LEAST16_MAX
#define M_ULEAST16_MAX UINT_LEAST16_MAX
#define M_LEAST32_MIN  INT_LEAST32_MIN
#define M_LEAST32_MAX  INT_LEAST32_MAX
#define M_ULEAST32_MAX UINT_LEAST32_MAX
#define M_LEAST64_MIN  INT_LEAST64_MIN
#define M_LEAST64_MAX  INT_LEAST64_MAX
#define M_ULEAST64_MAX UINT_LEAST64_MAX

// Max:

#define M_MAX_MIN  INTMAX_MIN
#define M_MAX_MAX  INTMAX_MAX
#define M_UMAX_MAX UINTMAX_MAX

// Size:

#define M_SSIZE_MIN PTRDIFF_MIN
#define M_SSIZE_MAX PTRDIFF_MAX
#define M_SIZE_MAX  SIZE_MAX

// Ptr:

#define M_PTR_MIN  INTPTR_MIN
#define M_PTR_MAX  INTPTR_MAX
#define M_UPTR_MAX UINTPTR_MAX

#endif
